// <auto-generated />
using System;
using App.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416064835_changetimezone")]
    partial class changetimezone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.DAL.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("594a3515-a34c-42fa-8b9f-649536330f57"),
                            Code = "Admin",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5238),
                            Description = "Quản trị viên",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5245),
                            Name = "Administrator",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("50e41743-40e5-43fe-9cc9-bf3ca57e6cc3"),
                            Code = "IT",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5264),
                            Description = "Công nghệ thông tin",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5264),
                            Name = "IT Service",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("0cab2e03-cb2f-4c82-afa4-2584127c1889"),
                            Code = "HR",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5268),
                            Description = "Nhân sự",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5268),
                            Name = "HR",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("a4571b49-9174-49d7-9c1a-ba8c916b1b55"),
                            Code = "ACC",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5272),
                            Description = "Kế toán",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(5272),
                            Name = "Accouting",
                            OrderIndex = 1
                        });
                });

            modelBuilder.Entity("App.DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequestForgetPassword")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastTimeLoginFail")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserLoginFailCount")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43ae9ab0-b5b7-42c1-a614-0914fc750514"),
                            Code = "SPX0001",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6059),
                            DepartmentId = new Guid("9e268971-e925-4825-80d3-dbb59fae2417"),
                            Email = "admin@gmail.com",
                            FirstName = "Administrator",
                            IsActived = true,
                            IsDeleted = false,
                            IsRequestForgetPassword = true,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6060),
                            Mobile = "1234566798",
                            OrderIndex = 1,
                            PasswordHash = "W9z/rq6anI3aSZUUaZvPjnXuaaqh8OmPX/Au5G2BK6k=",
                            PasswordSalt = "GtXTz62dhU29RX8yhoww45BR6z9elYdTeXHAvuao6KU=",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("594a3515-a34c-42fa-8b9f-649536330f57"),
                            UserLoginFailCount = 0,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("bc6bab7a-67ca-4e2e-bde1-a51c44e58091"),
                            Code = "SPX0002",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6095),
                            DepartmentId = new Guid("71822f66-6763-47cd-aea7-2269f495c733"),
                            Email = "accounting@gmail.com",
                            FirstName = "Accounting",
                            IsActived = true,
                            IsDeleted = false,
                            IsRequestForgetPassword = true,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6096),
                            Mobile = "1234566798",
                            OrderIndex = 1,
                            PasswordHash = "W9z/rq6anI3aSZUUaZvPjnXuaaqh8OmPX/Au5G2BK6k=",
                            PasswordSalt = "GtXTz62dhU29RX8yhoww45BR6z9elYdTeXHAvuao6KU=",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = new Guid("a4571b49-9174-49d7-9c1a-ba8c916b1b55"),
                            UserLoginFailCount = 0,
                            UserName = "accounting@gmail.com"
                        });
                });

            modelBuilder.Entity("App.DAL.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3a5878f-0a7c-4ecc-84f0-452d63a1b3e5"),
                            Code = "D-IT",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6014),
                            Description = "Công nghệ thông tin",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6015),
                            Name = "IT Service",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("9e268971-e925-4825-80d3-dbb59fae2417"),
                            Code = "D-HR",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6020),
                            Description = "Nhân sự",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6021),
                            Name = "HR",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("71822f66-6763-47cd-aea7-2269f495c733"),
                            Code = "D-ACC",
                            CreatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6023),
                            Description = "Kế toán",
                            IsActived = true,
                            IsDeleted = false,
                            LastUpdatedDate = new DateTime(2026, 4, 16, 6, 48, 32, 289, DateTimeKind.Utc).AddTicks(6024),
                            Name = "Accouting",
                            OrderIndex = 1
                        });
                });

            modelBuilder.Entity("App.DAL.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("App.DAL.Entities.PermissionModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PermissionModules");
                });

            modelBuilder.Entity("App.DAL.Entities.RolePermissionModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("PermissionModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RolePermissionModules");
                });

            modelBuilder.Entity("App.DAL.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIPN")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturnUrl")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Vnp_Amount")
                        .HasColumnType("float");

                    b.Property<string>("Vnp_Command")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Vnp_CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vnp_CurrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Vnp_ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vnp_IpAddr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_Locale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_OrderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_OrderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_ReturnUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_SecureHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TmnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("App.DAL.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("PerissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("App.DAL.Entities.VnpIpnLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Vnp_Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_BankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_BankTranNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_OrderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Vnp_PayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vnp_ResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_SecureHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TmnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TransactionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("vnpIpnLogs");
                });

            modelBuilder.Entity("App.DAL.Entities.VnpReturnUrlLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastUpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Vnp_Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_BankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_BankTranNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_OrderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Vnp_PayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vnp_ResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_SecureHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TmnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TransactionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TransactionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vnp_TxnRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VnpReturnUrlLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
